spring:
  web:
    resources:
      static-locations: file:/Users/zengxiangrui/DistributedProject/StudentSystem/static/
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/user/**
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/authentication/**
        - id: curriculum-management-service
          uri: lb://curriculum-management-service
          predicates:
            - Path=/curriculum/**
        - id: publish-service
          uri: lb://publish-service
          predicates:
            - Path=/publish/**
        - id: course-selection-service
          uri: lb://course-selection-service
          predicates:
            - Path=/selection/**
health:
  auth:
    excludePaths:
      - /authentication/**
logging:
  level:
    org.springframework.cloud.gateway: debug