springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /api-docs
spring:
  data:
    redis:
      host: 192.168.202.134
      password: root1234
      port: 6379
