springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /api-docs
spring:
  datasource:
    dynamic:
      primary: master_student
      strict: false
      datasource:
        master_student:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_student?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_teacher:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_teacher?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.202.134
      password: root1234
      port: 6379
