spring:
  datasource:
    dynamic:
      primary: master_student
      strict: false
      datasource:
        master_student:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_user?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_class:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_class?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_teacher:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_teacher?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_college:
          username: root
          password: root1234
          url: jdbc:mysql://127.0.0.1/student_college?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /api-docs
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true